server:
  port: 8082
spring:
  application:
    name: gigachat
  cloud:
    openfeign:
      client:
        config:
          ai:
            url: https://gigachat.devices.sberbank.ru
            loggerLevel: full

          aiAuth:
            loggerLevel: full
            url: https://ngw.devices.sberbank.ru:9443
ai:
  payload: 'scope=GIGACHAT_API_PERS'
  clientSecret: "1dd4675d-1f16-41a5-a711-f0b76a8676b6"
  authData: "MWRkNDY3NWQtMWYxNi00MWE1LWE3MTEtZjBiNzZhODY3NmI2OjY5MzUzNjZkLWVmYWEtNGY3OS1iOGFhLWEzN2UwYzBjZmU0Mg=="

prompt:
  translate: "Переведи в формат json слово %s"

cache:
  name: token
  key: ai-token




